import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "admin",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Bicycle 1",
      category: "T type",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "T",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Bicycle 2",
      category: "Y type",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Y",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Bicycle 3",
      category: "T type",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "T",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Bicycle 4",
      category: "T type",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "T",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Bicycle 5",
      category: "Y type",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Y",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Bicycle 6",
      category: "Y type",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Y",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
